### ISSUE TITLE
Phpenv actually installing rbenv

### ISSUE THREAD

**Issue by tdeekens** [CHH/phpenv#35]
...I am on Mac OS 10.10.1 installing `phpenv` via `homebrew` with `$brew install phpenv` while after running the install-script. After typing `phpenv` in my shell I get `rbenv 0.4.0` output. Is this due to the line https://github.com/CHH/phpenv/blob/master/bin/phpenv-install.sh#L26 indicating that the actually rbenv is installed right now?

Cheers.

**Comment by dsbaars** [comment]
Same here it seems...

**Comment by evoactivity** [comment]
also getting this

**Comment by ydesgagn** [comment]
Try phpenv install -l. This will give you a list of ruby versions to install instead of php versions.
