### ISSUE TITLE
Totally b0rk'd on Mac OS X

### ISSUE THREAD

**Issue by skyzyx** [CHH/phpenv#5]
Getting readline errors preventing environment variables from being set correctly.

**Comment by CHH** [comment]
Yeah, for now it's really not ready for usage on other systems than Linux, due to the limitiations of BSD's readlink implementation. There's a workaround for this, but as I've no Mac, there's no way I can test this.

Once I've my new Macbook, I will look into it, for sure.

**Comment by CHH** [comment]
I've now removed the usage of `readlink` and it should work now.

Could you try it please?

Thank you again for bringing this issue up!
